# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e65cd48feb024481c13dc7c98c3a7578b516d07f9cfb1db3861bb45834f7b92b1b80b21c2b61902ff7a292e5ce9ceeda9cd63118a66be8ebcc35c9bd77a5158d

test:
  secret_key_base: 929f109053e9edb5d3d1fc3278cc5a33bb1da2e93943d0b196add9427d385e8ef5ff420289b04fa59064fbe60b04090888fbf9486d03042d8432dd389f7cafd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
